// school-data.js — GrizzNet School Configuration
// Generated by the editor at /editor.html
// Do not edit manually — use the editor instead.

const SCHOOL_DATA = {

  // ── Graduation ──────────────────────────────────────────────────────────
  gradTotalCredits: "230",

  gradColumns: ["Subject Area", "Credits Required"],

  gradRequirements: [
    ["English / Language Arts", "40 (4 years)"],
    ["Math",                    "20–30"],
    ["Science",                 "20"],
    ["Social Studies / History","30"],
    ["Physical Education",      "20"],
    ["Health",                  "5"],
    ["Fine Arts or CTE",        "10"],
    ["Electives",               "Remaining"]
  ],

  gradOtherRequirements: "",
  gradCreditCheck: "",

  // ── Financial Aid ────────────────────────────────────────────────────────
  aidLocalScholarships: "",

  // ── Self-Advocacy ────────────────────────────────────────────────────────
  advocacyBilingualContact: "",

  // ── Handbook ─────────────────────────────────────────────────────────────
  handbookAttendance:     "",
  handbookCellPhone:      "",
  handbookDressCode:      "",
  handbookAcademicHonesty:"",
  handbookGrading:        "",
  handbookDiscipline:     "",
  handbookScheduleChange: "",
  handbookCampusAccess:   "",

  // ── Support ───────────────────────────────────────────────────────────────
  supportCounselors:   "",
  supportPsychologist: "",
  supportWellness:     "",
  supportSocialWorker: "",
  supportCheckIn:      "",
  supportCommunity:    "",
};
