// school-data.js — Student Hub School Configuration
// Generated by the editor at /hub-editor.html
// Do not edit manually — use the editor instead.
//
// Any field left empty here that has a matching Course Catalog value
// (grad requirements, counselors) will fall back to catalog data,
// so you don't have to enter the same information twice.

const SCHOOL_DATA = {

  // ── Graduation ──────────────────────────────────────────────────────────
  // Leave gradRequirements empty to fall back to Course Catalog's imported
  // grad requirements table (populated by the DOCX importer).
  gradTotalCredits: "",

  gradColumns: ["Subject Area", "Credits Required"],

  gradRequirements: [],

  gradOtherRequirements: "",
  gradCreditCheck: "",

  // ── Financial Aid ────────────────────────────────────────────────────────
  aidLocalScholarships: "",

  // ── Self-Advocacy ────────────────────────────────────────────────────────
  advocacyBilingualContact: "",

  // ── Handbook ─────────────────────────────────────────────────────────────
  handbookAttendance:     "",
  handbookCellPhone:      "",
  handbookDressCode:      "",
  handbookAcademicHonesty:"",
  handbookGrading:        "",
  handbookDiscipline:     "",
  handbookScheduleChange: "",
  handbookCampusAccess:   "",

  // ── Support ───────────────────────────────────────────────────────────────
  // Leave supportCounselors empty to fall back to the Course Catalog's
  // counselors list (populated by the DOCX importer).
  supportCounselors:   "",
  supportPsychologist: "",
  supportWellness:     "",
  supportSocialWorker: "",
  supportCheckIn:      "",
  supportCommunity:    "",
};
